### ISSUE TITLE
Frame Orientation

### ISSUE THREAD

**Issue by inveni0** [alexstaravoitau/MetalRenderCamera#5]
It seems that setting the frame orientation (for portrait) doesn't work.

`self.frameOrientation = AVCaptureVideoOrientation.portrait`

Do you have an example of how to do this?

**Comment by navoshta** [comment]
Hi @inveni0 — sorry, I didn't look into this project for a while, so won't be able to help. But if you manage to get a fix for it, feel free to submit a PR. 🙃

**Comment by yusuftor** [comment]
@inveni0 I have the same problem. Did you find a solution to that?

**Comment by navoshta** [comment]
Sorry for not being active on this repo — I haven't touched it in a while, but if you would like to submit a PR with this change that would be of huge help.

**Comment by alexstaravoitau** [comment]
Frame orientation defaults to portrait now.
