### ISSUE TITLE
MacOS?

### ISSUE THREAD

**Issue by KTRosenberg** [alexstaravoitau/MetalRenderCamera#6]
Metal has long worked on macos. Is it safe to remove the compiletime arch checks, or is there something that could go wrong implicitly?

**Comment by navoshta** [comment]
@KTRosenberg I haven't worked with Metal on macOS I'm afraid, so not sure if checks can be just removed, or if any other checks are needed instead.  Sorry for not being active on this repo — I haven't touched it in a while, but if you would like to submit a PR that would be of huge help.
